resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/apache/superset-kubernetes-operator
  newName: ghcr.io/apache/superset-kubernetes-operator
  newTag: latest
