# This rule is not used by the project superset-kubernetes-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to superset.apache.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: superset-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: supersettask-viewer-role
rules:
- apiGroups:
  - superset.apache.org
  resources:
  - supersettasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - superset.apache.org
  resources:
  - supersettasks/status
  verbs:
  - get
