//go:build !ignore_autogenerated

/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/api/autoscaling/v2"
	"k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminUserSpec) DeepCopyInto(out *AdminUserSpec) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminUserSpec.
func (in *AdminUserSpec) DeepCopy() *AdminUserSpec {
	if in == nil {
		return nil
	}
	out := new(AdminUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]v2.MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseTaskSpec) DeepCopyInto(out *BaseTaskSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(string)
		**out = **in
	}
	if in.RequiresDrain != nil {
		in, out := &in.RequiresDrain, &out.RequiresDrain
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseTaskSpec.
func (in *BaseTaskSpec) DeepCopy() *BaseTaskSpec {
	if in == nil {
		return nil
	}
	out := new(BaseTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryBeatComponentSpec) DeepCopyInto(out *CeleryBeatComponentSpec) {
	*out = *in
	if in.DeploymentTemplate != nil {
		in, out := &in.DeploymentTemplate, &out.DeploymentTemplate
		*out = new(DeploymentTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplate)
		(*in).DeepCopyInto(*out)
	}
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.SQLAlchemyEngineOptions != nil {
		in, out := &in.SQLAlchemyEngineOptions, &out.SQLAlchemyEngineOptions
		*out = new(SQLAlchemyEngineOptionsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryBeatComponentSpec.
func (in *CeleryBeatComponentSpec) DeepCopy() *CeleryBeatComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CeleryBeatComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryFlowerComponentSpec) DeepCopyInto(out *CeleryFlowerComponentSpec) {
	*out = *in
	in.ScalableComponentSpec.DeepCopyInto(&out.ScalableComponentSpec)
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryFlowerComponentSpec.
func (in *CeleryFlowerComponentSpec) DeepCopy() *CeleryFlowerComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CeleryFlowerComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryWorkerComponentSpec) DeepCopyInto(out *CeleryWorkerComponentSpec) {
	*out = *in
	in.ScalableComponentSpec.DeepCopyInto(&out.ScalableComponentSpec)
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.Celery != nil {
		in, out := &in.Celery, &out.Celery
		*out = new(CeleryWorkerProcessSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SQLAlchemyEngineOptions != nil {
		in, out := &in.SQLAlchemyEngineOptions, &out.SQLAlchemyEngineOptions
		*out = new(SQLAlchemyEngineOptionsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryWorkerComponentSpec.
func (in *CeleryWorkerComponentSpec) DeepCopy() *CeleryWorkerComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CeleryWorkerComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeleryWorkerProcessSpec) DeepCopyInto(out *CeleryWorkerProcessSpec) {
	*out = *in
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(string)
		**out = **in
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(string)
		**out = **in
	}
	if in.Optimization != nil {
		in, out := &in.Optimization, &out.Optimization
		*out = new(string)
		**out = **in
	}
	if in.MaxTasksPerChild != nil {
		in, out := &in.MaxTasksPerChild, &out.MaxTasksPerChild
		*out = new(int32)
		**out = **in
	}
	if in.MaxMemoryPerChild != nil {
		in, out := &in.MaxMemoryPerChild, &out.MaxMemoryPerChild
		*out = new(int32)
		**out = **in
	}
	if in.PrefetchMultiplier != nil {
		in, out := &in.PrefetchMultiplier, &out.PrefetchMultiplier
		*out = new(int32)
		**out = **in
	}
	if in.SoftTimeLimit != nil {
		in, out := &in.SoftTimeLimit, &out.SoftTimeLimit
		*out = new(int32)
		**out = **in
	}
	if in.TimeLimit != nil {
		in, out := &in.TimeLimit, &out.TimeLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeleryWorkerProcessSpec.
func (in *CeleryWorkerProcessSpec) DeepCopy() *CeleryWorkerProcessSpec {
	if in == nil {
		return nil
	}
	out := new(CeleryWorkerProcessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildComponentStatus) DeepCopyInto(out *ChildComponentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildComponentStatus.
func (in *ChildComponentStatus) DeepCopy() *ChildComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ChildComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloneSourceSpec) DeepCopyInto(out *CloneSourceSpec) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.PasswordFrom != nil {
		in, out := &in.PasswordFrom, &out.PasswordFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloneSourceSpec.
func (in *CloneSourceSpec) DeepCopy() *CloneSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CloneSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloneTaskSpec) DeepCopyInto(out *CloneTaskSpec) {
	*out = *in
	in.SchedulableBaseTaskSpec.DeepCopyInto(&out.SchedulableBaseTaskSpec)
	in.Source.DeepCopyInto(&out.Source)
	if in.ExcludeTables != nil {
		in, out := &in.ExcludeTables, &out.ExcludeTables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeTableData != nil {
		in, out := &in.ExcludeTableData, &out.ExcludeTableData
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.PodRetention != nil {
		in, out := &in.PodRetention, &out.PodRetention
		*out = new(PodRetentionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloneTaskSpec.
func (in *CloneTaskSpec) DeepCopy() *CloneTaskSpec {
	if in == nil {
		return nil
	}
	out := new(CloneTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentRefStatus) DeepCopyInto(out *ComponentRefStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentRefStatus.
func (in *ComponentRefStatus) DeepCopy() *ComponentRefStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentRefStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentServiceSpec) DeepCopyInto(out *ComponentServiceSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GatewayPath != nil {
		in, out := &in.GatewayPath, &out.GatewayPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentServiceSpec.
func (in *ComponentServiceSpec) DeepCopy() *ComponentServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageOverrideSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatusMap) DeepCopyInto(out *ComponentStatusMap) {
	*out = *in
	if in.WebServer != nil {
		in, out := &in.WebServer, &out.WebServer
		*out = new(ComponentRefStatus)
		**out = **in
	}
	if in.CeleryWorker != nil {
		in, out := &in.CeleryWorker, &out.CeleryWorker
		*out = new(ComponentRefStatus)
		**out = **in
	}
	if in.CeleryBeat != nil {
		in, out := &in.CeleryBeat, &out.CeleryBeat
		*out = new(ComponentRefStatus)
		**out = **in
	}
	if in.CeleryFlower != nil {
		in, out := &in.CeleryFlower, &out.CeleryFlower
		*out = new(ComponentRefStatus)
		**out = **in
	}
	if in.WebsocketServer != nil {
		in, out := &in.WebsocketServer, &out.WebsocketServer
		*out = new(ComponentRefStatus)
		**out = **in
	}
	if in.McpServer != nil {
		in, out := &in.McpServer, &out.McpServer
		*out = new(ComponentRefStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatusMap.
func (in *ComponentStatusMap) DeepCopy() *ComponentStatusMap {
	if in == nil {
		return nil
	}
	out := new(ComponentStatusMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerTemplate) DeepCopyInto(out *ContainerTemplate) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ContainerPort, len(*in))
		copy(*out, *in)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(v1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerTemplate.
func (in *ContainerTemplate) DeepCopy() *ContainerTemplate {
	if in == nil {
		return nil
	}
	out := new(ContainerTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentTemplate) DeepCopyInto(out *DeploymentTemplate) {
	*out = *in
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.MinReadySeconds != nil {
		in, out := &in.MinReadySeconds, &out.MinReadySeconds
		*out = new(int32)
		**out = **in
	}
	if in.ProgressDeadlineSeconds != nil {
		in, out := &in.ProgressDeadlineSeconds, &out.ProgressDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(appsv1.DeploymentStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentTemplate.
func (in *DeploymentTemplate) DeepCopy() *DeploymentTemplate {
	if in == nil {
		return nil
	}
	out := new(DeploymentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlatComponentSpec) DeepCopyInto(out *FlatComponentSpec) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.DeploymentTemplate != nil {
		in, out := &in.DeploymentTemplate, &out.DeploymentTemplate
		*out = new(DeploymentTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PDBSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlatComponentSpec.
func (in *FlatComponentSpec) DeepCopy() *FlatComponentSpec {
	if in == nil {
		return nil
	}
	out := new(FlatComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	in.GatewayRef.DeepCopyInto(&out.GatewayRef)
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]apisv1.Hostname, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GunicornSpec) DeepCopyInto(out *GunicornSpec) {
	*out = *in
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(string)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(int32)
		**out = **in
	}
	if in.Threads != nil {
		in, out := &in.Threads, &out.Threads
		*out = new(int32)
		**out = **in
	}
	if in.WorkerClass != nil {
		in, out := &in.WorkerClass, &out.WorkerClass
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int32)
		**out = **in
	}
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(int32)
		**out = **in
	}
	if in.MaxRequests != nil {
		in, out := &in.MaxRequests, &out.MaxRequests
		*out = new(int32)
		**out = **in
	}
	if in.MaxRequestsJitter != nil {
		in, out := &in.MaxRequestsJitter, &out.MaxRequestsJitter
		*out = new(int32)
		**out = **in
	}
	if in.LimitRequestLine != nil {
		in, out := &in.LimitRequestLine, &out.LimitRequestLine
		*out = new(int32)
		**out = **in
	}
	if in.LimitRequestFieldSize != nil {
		in, out := &in.LimitRequestFieldSize, &out.LimitRequestFieldSize
		*out = new(int32)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GunicornSpec.
func (in *GunicornSpec) DeepCopy() *GunicornSpec {
	if in == nil {
		return nil
	}
	out := new(GunicornSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageOverrideSpec) DeepCopyInto(out *ImageOverrideSpec) {
	*out = *in
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageOverrideSpec.
func (in *ImageOverrideSpec) DeepCopy() *ImageOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(ImageOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressHost) DeepCopyInto(out *IngressHost) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]IngressPath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressHost.
func (in *IngressHost) DeepCopy() *IngressHost {
	if in == nil {
		return nil
	}
	out := new(IngressHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressPath) DeepCopyInto(out *IngressPath) {
	*out = *in
	if in.PathType != nil {
		in, out := &in.PathType, &out.PathType
		*out = new(networkingv1.PathType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressPath.
func (in *IngressPath) DeepCopy() *IngressPath {
	if in == nil {
		return nil
	}
	out := new(IngressPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]IngressHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]networkingv1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitTaskSpec) DeepCopyInto(out *InitTaskSpec) {
	*out = *in
	in.BaseTaskSpec.DeepCopyInto(&out.BaseTaskSpec)
	if in.AdminUser != nil {
		in, out := &in.AdminUser, &out.AdminUser
		*out = new(AdminUserSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadExamples != nil {
		in, out := &in.LoadExamples, &out.LoadExamples
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitTaskSpec.
func (in *InitTaskSpec) DeepCopy() *InitTaskSpec {
	if in == nil {
		return nil
	}
	out := new(InitTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleSpec) DeepCopyInto(out *LifecycleSpec) {
	*out = *in
	if in.UpgradeMode != nil {
		in, out := &in.UpgradeMode, &out.UpgradeMode
		*out = new(string)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageOverrideSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.PodRetention != nil {
		in, out := &in.PodRetention, &out.PodRetention
		*out = new(PodRetentionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.SQLAlchemyEngineOptions != nil {
		in, out := &in.SQLAlchemyEngineOptions, &out.SQLAlchemyEngineOptions
		*out = new(SQLAlchemyEngineOptionsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Clone != nil {
		in, out := &in.Clone, &out.Clone
		*out = new(CloneTaskSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = new(MigrateTaskSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(InitTaskSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleSpec.
func (in *LifecycleSpec) DeepCopy() *LifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(LifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleStatus) DeepCopyInto(out *LifecycleStatus) {
	*out = *in
	if in.Clone != nil {
		in, out := &in.Clone, &out.Clone
		*out = new(TaskRefStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = new(TaskRefStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(TaskRefStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(UpgradeContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleStatus.
func (in *LifecycleStatus) DeepCopy() *LifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(LifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpServerComponentSpec) DeepCopyInto(out *McpServerComponentSpec) {
	*out = *in
	in.ScalableComponentSpec.DeepCopyInto(&out.ScalableComponentSpec)
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SQLAlchemyEngineOptions != nil {
		in, out := &in.SQLAlchemyEngineOptions, &out.SQLAlchemyEngineOptions
		*out = new(SQLAlchemyEngineOptionsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpServerComponentSpec.
func (in *McpServerComponentSpec) DeepCopy() *McpServerComponentSpec {
	if in == nil {
		return nil
	}
	out := new(McpServerComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetastoreSpec) DeepCopyInto(out *MetastoreSpec) {
	*out = *in
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
	if in.URIFrom != nil {
		in, out := &in.URIFrom, &out.URIFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.PasswordFrom != nil {
		in, out := &in.PasswordFrom, &out.PasswordFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetastoreSpec.
func (in *MetastoreSpec) DeepCopy() *MetastoreSpec {
	if in == nil {
		return nil
	}
	out := new(MetastoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrateTaskSpec) DeepCopyInto(out *MigrateTaskSpec) {
	*out = *in
	in.BaseTaskSpec.DeepCopyInto(&out.BaseTaskSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrateTaskSpec.
func (in *MigrateTaskSpec) DeepCopy() *MigrateTaskSpec {
	if in == nil {
		return nil
	}
	out := new(MigrateTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(ServiceMonitorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.ExtraIngress != nil {
		in, out := &in.ExtraIngress, &out.ExtraIngress
		*out = make([]networkingv1.NetworkPolicyIngressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraEgress != nil {
		in, out := &in.ExtraEgress, &out.ExtraEgress
		*out = make([]networkingv1.NetworkPolicyEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkingSpec) DeepCopyInto(out *NetworkingSpec) {
	*out = *in
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkingSpec.
func (in *NetworkingSpec) DeepCopy() *NetworkingSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBSpec) DeepCopyInto(out *PDBSpec) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBSpec.
func (in *PDBSpec) DeepCopy() *PDBSpec {
	if in == nil {
		return nil
	}
	out := new(PDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRetentionSpec) DeepCopyInto(out *PodRetentionSpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRetentionSpec.
func (in *PodRetentionSpec) DeepCopy() *PodRetentionSpec {
	if in == nil {
		return nil
	}
	out := new(PodRetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTemplate) DeepCopyInto(out *PodTemplate) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostAliases != nil {
		in, out := &in.HostAliases, &out.HostAliases
		*out = make([]v1.HostAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.DNSPolicy != nil {
		in, out := &in.DNSPolicy, &out.DNSPolicy
		*out = new(v1.DNSPolicy)
		**out = **in
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(v1.PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.ShareProcessNamespace != nil {
		in, out := &in.ShareProcessNamespace, &out.ShareProcessNamespace
		*out = new(bool)
		**out = **in
	}
	if in.EnableServiceLinks != nil {
		in, out := &in.EnableServiceLinks, &out.EnableServiceLinks
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTemplate.
func (in *PodTemplate) DeepCopy() *PodTemplate {
	if in == nil {
		return nil
	}
	out := new(PodTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLAlchemyEngineOptionsSpec) DeepCopyInto(out *SQLAlchemyEngineOptionsSpec) {
	*out = *in
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(string)
		**out = **in
	}
	if in.PoolSize != nil {
		in, out := &in.PoolSize, &out.PoolSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxOverflow != nil {
		in, out := &in.MaxOverflow, &out.MaxOverflow
		*out = new(int32)
		**out = **in
	}
	if in.PoolRecycle != nil {
		in, out := &in.PoolRecycle, &out.PoolRecycle
		*out = new(int32)
		**out = **in
	}
	if in.PoolPrePing != nil {
		in, out := &in.PoolPrePing, &out.PoolPrePing
		*out = new(bool)
		**out = **in
	}
	if in.PoolTimeout != nil {
		in, out := &in.PoolTimeout, &out.PoolTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLAlchemyEngineOptionsSpec.
func (in *SQLAlchemyEngineOptionsSpec) DeepCopy() *SQLAlchemyEngineOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(SQLAlchemyEngineOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalableComponentSpec) DeepCopyInto(out *ScalableComponentSpec) {
	*out = *in
	if in.DeploymentTemplate != nil {
		in, out := &in.DeploymentTemplate, &out.DeploymentTemplate
		*out = new(DeploymentTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PDBSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalableComponentSpec.
func (in *ScalableComponentSpec) DeepCopy() *ScalableComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ScalableComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulableBaseTaskSpec) DeepCopyInto(out *SchedulableBaseTaskSpec) {
	*out = *in
	in.BaseTaskSpec.DeepCopyInto(&out.BaseTaskSpec)
	if in.CronSchedule != nil {
		in, out := &in.CronSchedule, &out.CronSchedule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulableBaseTaskSpec.
func (in *SchedulableBaseTaskSpec) DeepCopy() *SchedulableBaseTaskSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulableBaseTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSpec) DeepCopyInto(out *ServiceAccountSpec) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSpec.
func (in *ServiceAccountSpec) DeepCopy() *ServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorSpec) DeepCopyInto(out *ServiceMonitorSpec) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ScrapeTimeout != nil {
		in, out := &in.ScrapeTimeout, &out.ScrapeTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorSpec.
func (in *ServiceMonitorSpec) DeepCopy() *ServiceMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Superset) DeepCopyInto(out *Superset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Superset.
func (in *Superset) DeepCopy() *Superset {
	if in == nil {
		return nil
	}
	out := new(Superset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Superset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryBeat) DeepCopyInto(out *SupersetCeleryBeat) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryBeat.
func (in *SupersetCeleryBeat) DeepCopy() *SupersetCeleryBeat {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryBeat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetCeleryBeat) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryBeatList) DeepCopyInto(out *SupersetCeleryBeatList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupersetCeleryBeat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryBeatList.
func (in *SupersetCeleryBeatList) DeepCopy() *SupersetCeleryBeatList {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryBeatList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetCeleryBeatList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryBeatSpec) DeepCopyInto(out *SupersetCeleryBeatSpec) {
	*out = *in
	in.FlatComponentSpec.DeepCopyInto(&out.FlatComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryBeatSpec.
func (in *SupersetCeleryBeatSpec) DeepCopy() *SupersetCeleryBeatSpec {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryBeatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryBeatStatus) DeepCopyInto(out *SupersetCeleryBeatStatus) {
	*out = *in
	in.ChildComponentStatus.DeepCopyInto(&out.ChildComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryBeatStatus.
func (in *SupersetCeleryBeatStatus) DeepCopy() *SupersetCeleryBeatStatus {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryBeatStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryFlower) DeepCopyInto(out *SupersetCeleryFlower) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryFlower.
func (in *SupersetCeleryFlower) DeepCopy() *SupersetCeleryFlower {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryFlower)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetCeleryFlower) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryFlowerList) DeepCopyInto(out *SupersetCeleryFlowerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupersetCeleryFlower, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryFlowerList.
func (in *SupersetCeleryFlowerList) DeepCopy() *SupersetCeleryFlowerList {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryFlowerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetCeleryFlowerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryFlowerSpec) DeepCopyInto(out *SupersetCeleryFlowerSpec) {
	*out = *in
	in.FlatComponentSpec.DeepCopyInto(&out.FlatComponentSpec)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryFlowerSpec.
func (in *SupersetCeleryFlowerSpec) DeepCopy() *SupersetCeleryFlowerSpec {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryFlowerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryFlowerStatus) DeepCopyInto(out *SupersetCeleryFlowerStatus) {
	*out = *in
	in.ChildComponentStatus.DeepCopyInto(&out.ChildComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryFlowerStatus.
func (in *SupersetCeleryFlowerStatus) DeepCopy() *SupersetCeleryFlowerStatus {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryFlowerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryWorker) DeepCopyInto(out *SupersetCeleryWorker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryWorker.
func (in *SupersetCeleryWorker) DeepCopy() *SupersetCeleryWorker {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetCeleryWorker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryWorkerList) DeepCopyInto(out *SupersetCeleryWorkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupersetCeleryWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryWorkerList.
func (in *SupersetCeleryWorkerList) DeepCopy() *SupersetCeleryWorkerList {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryWorkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetCeleryWorkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryWorkerSpec) DeepCopyInto(out *SupersetCeleryWorkerSpec) {
	*out = *in
	in.FlatComponentSpec.DeepCopyInto(&out.FlatComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryWorkerSpec.
func (in *SupersetCeleryWorkerSpec) DeepCopy() *SupersetCeleryWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetCeleryWorkerStatus) DeepCopyInto(out *SupersetCeleryWorkerStatus) {
	*out = *in
	in.ChildComponentStatus.DeepCopyInto(&out.ChildComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetCeleryWorkerStatus.
func (in *SupersetCeleryWorkerStatus) DeepCopy() *SupersetCeleryWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(SupersetCeleryWorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetLifecycleTask) DeepCopyInto(out *SupersetLifecycleTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetLifecycleTask.
func (in *SupersetLifecycleTask) DeepCopy() *SupersetLifecycleTask {
	if in == nil {
		return nil
	}
	out := new(SupersetLifecycleTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetLifecycleTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetLifecycleTaskList) DeepCopyInto(out *SupersetLifecycleTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupersetLifecycleTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetLifecycleTaskList.
func (in *SupersetLifecycleTaskList) DeepCopy() *SupersetLifecycleTaskList {
	if in == nil {
		return nil
	}
	out := new(SupersetLifecycleTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetLifecycleTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetLifecycleTaskSpec) DeepCopyInto(out *SupersetLifecycleTaskSpec) {
	*out = *in
	in.FlatComponentSpec.DeepCopyInto(&out.FlatComponentSpec)
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
	if in.PodRetention != nil {
		in, out := &in.PodRetention, &out.PodRetention
		*out = new(PodRetentionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetLifecycleTaskSpec.
func (in *SupersetLifecycleTaskSpec) DeepCopy() *SupersetLifecycleTaskSpec {
	if in == nil {
		return nil
	}
	out := new(SupersetLifecycleTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetLifecycleTaskStatus) DeepCopyInto(out *SupersetLifecycleTaskStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetLifecycleTaskStatus.
func (in *SupersetLifecycleTaskStatus) DeepCopy() *SupersetLifecycleTaskStatus {
	if in == nil {
		return nil
	}
	out := new(SupersetLifecycleTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetList) DeepCopyInto(out *SupersetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Superset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetList.
func (in *SupersetList) DeepCopy() *SupersetList {
	if in == nil {
		return nil
	}
	out := new(SupersetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetMcpServer) DeepCopyInto(out *SupersetMcpServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetMcpServer.
func (in *SupersetMcpServer) DeepCopy() *SupersetMcpServer {
	if in == nil {
		return nil
	}
	out := new(SupersetMcpServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetMcpServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetMcpServerList) DeepCopyInto(out *SupersetMcpServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupersetMcpServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetMcpServerList.
func (in *SupersetMcpServerList) DeepCopy() *SupersetMcpServerList {
	if in == nil {
		return nil
	}
	out := new(SupersetMcpServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetMcpServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetMcpServerSpec) DeepCopyInto(out *SupersetMcpServerSpec) {
	*out = *in
	in.FlatComponentSpec.DeepCopyInto(&out.FlatComponentSpec)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetMcpServerSpec.
func (in *SupersetMcpServerSpec) DeepCopy() *SupersetMcpServerSpec {
	if in == nil {
		return nil
	}
	out := new(SupersetMcpServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetMcpServerStatus) DeepCopyInto(out *SupersetMcpServerStatus) {
	*out = *in
	in.ChildComponentStatus.DeepCopyInto(&out.ChildComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetMcpServerStatus.
func (in *SupersetMcpServerStatus) DeepCopy() *SupersetMcpServerStatus {
	if in == nil {
		return nil
	}
	out := new(SupersetMcpServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetSpec) DeepCopyInto(out *SupersetSpec) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
	if in.DeploymentTemplate != nil {
		in, out := &in.DeploymentTemplate, &out.DeploymentTemplate
		*out = new(DeploymentTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PDBSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.SecretKey != nil {
		in, out := &in.SecretKey, &out.SecretKey
		*out = new(string)
		**out = **in
	}
	if in.SecretKeyFrom != nil {
		in, out := &in.SecretKeyFrom, &out.SecretKeyFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Metastore != nil {
		in, out := &in.Metastore, &out.Metastore
		*out = new(MetastoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Valkey != nil {
		in, out := &in.Valkey, &out.Valkey
		*out = new(ValkeySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.SQLAlchemyEngineOptions != nil {
		in, out := &in.SQLAlchemyEngineOptions, &out.SQLAlchemyEngineOptions
		*out = new(SQLAlchemyEngineOptionsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WebServer != nil {
		in, out := &in.WebServer, &out.WebServer
		*out = new(WebServerComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CeleryWorker != nil {
		in, out := &in.CeleryWorker, &out.CeleryWorker
		*out = new(CeleryWorkerComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CeleryBeat != nil {
		in, out := &in.CeleryBeat, &out.CeleryBeat
		*out = new(CeleryBeatComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CeleryFlower != nil {
		in, out := &in.CeleryFlower, &out.CeleryFlower
		*out = new(CeleryFlowerComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WebsocketServer != nil {
		in, out := &in.WebsocketServer, &out.WebsocketServer
		*out = new(WebsocketServerComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.McpServer != nil {
		in, out := &in.McpServer, &out.McpServer
		*out = new(McpServerComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(LifecycleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(NetworkingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(ServiceAccountSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetSpec.
func (in *SupersetSpec) DeepCopy() *SupersetSpec {
	if in == nil {
		return nil
	}
	out := new(SupersetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetStatus) DeepCopyInto(out *SupersetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = new(ComponentStatusMap)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(LifecycleStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetStatus.
func (in *SupersetStatus) DeepCopy() *SupersetStatus {
	if in == nil {
		return nil
	}
	out := new(SupersetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetWebServer) DeepCopyInto(out *SupersetWebServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetWebServer.
func (in *SupersetWebServer) DeepCopy() *SupersetWebServer {
	if in == nil {
		return nil
	}
	out := new(SupersetWebServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetWebServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetWebServerList) DeepCopyInto(out *SupersetWebServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupersetWebServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetWebServerList.
func (in *SupersetWebServerList) DeepCopy() *SupersetWebServerList {
	if in == nil {
		return nil
	}
	out := new(SupersetWebServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetWebServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetWebServerSpec) DeepCopyInto(out *SupersetWebServerSpec) {
	*out = *in
	in.FlatComponentSpec.DeepCopyInto(&out.FlatComponentSpec)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetWebServerSpec.
func (in *SupersetWebServerSpec) DeepCopy() *SupersetWebServerSpec {
	if in == nil {
		return nil
	}
	out := new(SupersetWebServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetWebServerStatus) DeepCopyInto(out *SupersetWebServerStatus) {
	*out = *in
	in.ChildComponentStatus.DeepCopyInto(&out.ChildComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetWebServerStatus.
func (in *SupersetWebServerStatus) DeepCopy() *SupersetWebServerStatus {
	if in == nil {
		return nil
	}
	out := new(SupersetWebServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetWebsocketServer) DeepCopyInto(out *SupersetWebsocketServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetWebsocketServer.
func (in *SupersetWebsocketServer) DeepCopy() *SupersetWebsocketServer {
	if in == nil {
		return nil
	}
	out := new(SupersetWebsocketServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetWebsocketServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetWebsocketServerList) DeepCopyInto(out *SupersetWebsocketServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupersetWebsocketServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetWebsocketServerList.
func (in *SupersetWebsocketServerList) DeepCopy() *SupersetWebsocketServerList {
	if in == nil {
		return nil
	}
	out := new(SupersetWebsocketServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupersetWebsocketServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetWebsocketServerSpec) DeepCopyInto(out *SupersetWebsocketServerSpec) {
	*out = *in
	in.FlatComponentSpec.DeepCopyInto(&out.FlatComponentSpec)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetWebsocketServerSpec.
func (in *SupersetWebsocketServerSpec) DeepCopy() *SupersetWebsocketServerSpec {
	if in == nil {
		return nil
	}
	out := new(SupersetWebsocketServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupersetWebsocketServerStatus) DeepCopyInto(out *SupersetWebsocketServerStatus) {
	*out = *in
	in.ChildComponentStatus.DeepCopyInto(&out.ChildComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupersetWebsocketServerStatus.
func (in *SupersetWebsocketServerStatus) DeepCopy() *SupersetWebsocketServerStatus {
	if in == nil {
		return nil
	}
	out := new(SupersetWebsocketServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRefStatus) DeepCopyInto(out *TaskRefStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.LastScheduledAt != nil {
		in, out := &in.LastScheduledAt, &out.LastScheduledAt
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleAt != nil {
		in, out := &in.NextScheduleAt, &out.NextScheduleAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRefStatus.
func (in *TaskRefStatus) DeepCopy() *TaskRefStatus {
	if in == nil {
		return nil
	}
	out := new(TaskRefStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeContext) DeepCopyInto(out *UpgradeContext) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeContext.
func (in *UpgradeContext) DeepCopy() *UpgradeContext {
	if in == nil {
		return nil
	}
	out := new(UpgradeContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyCacheSpec) DeepCopyInto(out *ValkeyCacheSpec) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(int32)
		**out = **in
	}
	if in.KeyPrefix != nil {
		in, out := &in.KeyPrefix, &out.KeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.DefaultTimeout != nil {
		in, out := &in.DefaultTimeout, &out.DefaultTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyCacheSpec.
func (in *ValkeyCacheSpec) DeepCopy() *ValkeyCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ValkeyCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyCelerySpec) DeepCopyInto(out *ValkeyCelerySpec) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyCelerySpec.
func (in *ValkeyCelerySpec) DeepCopy() *ValkeyCelerySpec {
	if in == nil {
		return nil
	}
	out := new(ValkeyCelerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyResultsBackendSpec) DeepCopyInto(out *ValkeyResultsBackendSpec) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(int32)
		**out = **in
	}
	if in.KeyPrefix != nil {
		in, out := &in.KeyPrefix, &out.KeyPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyResultsBackendSpec.
func (in *ValkeyResultsBackendSpec) DeepCopy() *ValkeyResultsBackendSpec {
	if in == nil {
		return nil
	}
	out := new(ValkeyResultsBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeySSLSpec) DeepCopyInto(out *ValkeySSLSpec) {
	*out = *in
	if in.CertRequired != nil {
		in, out := &in.CertRequired, &out.CertRequired
		*out = new(string)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.CACertFile != nil {
		in, out := &in.CACertFile, &out.CACertFile
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeySSLSpec.
func (in *ValkeySSLSpec) DeepCopy() *ValkeySSLSpec {
	if in == nil {
		return nil
	}
	out := new(ValkeySSLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeySpec) DeepCopyInto(out *ValkeySpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.PasswordFrom != nil {
		in, out := &in.PasswordFrom, &out.PasswordFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(ValkeySSLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(ValkeyCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DataCache != nil {
		in, out := &in.DataCache, &out.DataCache
		*out = new(ValkeyCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.FilterStateCache != nil {
		in, out := &in.FilterStateCache, &out.FilterStateCache
		*out = new(ValkeyCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExploreFormDataCache != nil {
		in, out := &in.ExploreFormDataCache, &out.ExploreFormDataCache
		*out = new(ValkeyCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ThumbnailCache != nil {
		in, out := &in.ThumbnailCache, &out.ThumbnailCache
		*out = new(ValkeyCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CeleryBroker != nil {
		in, out := &in.CeleryBroker, &out.CeleryBroker
		*out = new(ValkeyCelerySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CeleryResultBackend != nil {
		in, out := &in.CeleryResultBackend, &out.CeleryResultBackend
		*out = new(ValkeyCelerySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ResultsBackend != nil {
		in, out := &in.ResultsBackend, &out.ResultsBackend
		*out = new(ValkeyResultsBackendSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeySpec.
func (in *ValkeySpec) DeepCopy() *ValkeySpec {
	if in == nil {
		return nil
	}
	out := new(ValkeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebServerComponentSpec) DeepCopyInto(out *WebServerComponentSpec) {
	*out = *in
	in.ScalableComponentSpec.DeepCopyInto(&out.ScalableComponentSpec)
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gunicorn != nil {
		in, out := &in.Gunicorn, &out.Gunicorn
		*out = new(GunicornSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SQLAlchemyEngineOptions != nil {
		in, out := &in.SQLAlchemyEngineOptions, &out.SQLAlchemyEngineOptions
		*out = new(SQLAlchemyEngineOptionsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebServerComponentSpec.
func (in *WebServerComponentSpec) DeepCopy() *WebServerComponentSpec {
	if in == nil {
		return nil
	}
	out := new(WebServerComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebsocketServerComponentSpec) DeepCopyInto(out *WebsocketServerComponentSpec) {
	*out = *in
	in.ScalableComponentSpec.DeepCopyInto(&out.ScalableComponentSpec)
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebsocketServerComponentSpec.
func (in *WebsocketServerComponentSpec) DeepCopy() *WebsocketServerComponentSpec {
	if in == nil {
		return nil
	}
	out := new(WebsocketServerComponentSpec)
	in.DeepCopyInto(out)
	return out
}
