#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Render the make-commands tables from the Makefile's `##@ Section` headers
# and `target: ## description` annotations into the contributing docs, between
# sentinel comments:
#
#   <!-- BEGIN MAKE-COMMANDS -->
#   ... generated block ...
#   <!-- END MAKE-COMMANDS -->
#
# The "General" and "Dependencies" sections are skipped — they contain `help`
# and tool-bootstrap targets that aren't user-facing. To surface a target in
# the docs, place it in a section other than those two.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAKEFILE="${REPO_ROOT}/Makefile"
TARGETS=(
  "${REPO_ROOT}/docs/contributing/development-setup.md"
)
SKIP_SECTIONS_RE='^(General|Dependencies)$'

table="$(awk -v skip_re="${SKIP_SECTIONS_RE}" '
  /^##@/ {
    section = substr($0, 5)
    sub(/^[ \t]+/, "", section)
    sub(/[ \t]+$/, "", section)
    if (section ~ skip_re) {
      skip = 1
    } else {
      skip = 0
      if (printed_section) print ""
      print "### " section
      print ""
      print "| Command | Description |"
      print "|---|---|"
      printed_section = 1
    }
    next
  }
  /^[a-zA-Z_0-9-]+:.*##/ {
    if (skip) next
    idx = index($0, "##")
    target = substr($0, 1, idx - 1)
    sub(/:.*$/, "", target)
    sub(/[ \t]+$/, "", target)
    desc = substr($0, idx + 2)
    sub(/^[ \t]+/, "", desc)
    sub(/[ \t]+$/, "", desc)
    printf "| `make %s` | %s |\n", target, desc
  }
' "${MAKEFILE}")"

block="$({
  echo '<!-- BEGIN MAKE-COMMANDS -->'
  echo '<!-- generated by `make codegen`; do not edit -->'
  echo "${table}"
  echo '<!-- END MAKE-COMMANDS -->'
})"

for file in "${TARGETS[@]}"; do
  if ! grep -q '<!-- BEGIN MAKE-COMMANDS -->' "${file}"; then
    echo "no sentinel block found in ${file}" >&2
    exit 1
  fi
  tmp="$(mktemp)"
  BLOCK="${block}" awk '
    /<!-- BEGIN MAKE-COMMANDS -->/ {
      print ENVIRON["BLOCK"]
      skip = 1
      next
    }
    /<!-- END MAKE-COMMANDS -->/ {
      skip = 0
      next
    }
    !skip { print }
  ' "${file}" > "${tmp}"
  mv "${tmp}" "${file}"
done
